plugins:
  recommendation_enable:
    default: false
    client: true
  recommendation_server:
    default: 'http://10.7.30.15:9000'
    client: false
  daily_retrain_time: 
    client: true
    default: "0 0 * * *"